package cn.linkey.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WF_CallBackService service = new WF_CallBackService();
 * WFCallBack portType = service.getWFCallBackPort();
 * portType.callback(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WF_CallBackService", targetNamespace = "http://server.ws.linkey.cn/", wsdlLocation = "http://localhost:8080/bpm/WF_CallBackPort?wsdl")
public class WFCallBackService extends Service {

    private final static URL WFCALLBACKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.linkey.ws.client.WFCallBackService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.linkey.ws.client.WFCallBackService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bpm/WF_CallBackPort?wsdl");
        }
        catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bpm/WF_CallBackPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WFCALLBACKSERVICE_WSDL_LOCATION = url;
    }

    public WFCallBackService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFCallBackService() {
        super(WFCALLBACKSERVICE_WSDL_LOCATION, new QName("http://server.ws.linkey.cn/", "WF_CallBackService"));
    }

    /**
     * 
     * @return returns WFCallBack
     */
    @WebEndpoint(name = "WF_CallBackPort")
    public WFCallBack getWFCallBackPort() {
        return super.getPort(new QName("http://server.ws.linkey.cn/", "WF_CallBackPort"), WFCallBack.class);
    }

}
