package cn.linkey.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WF_OpenProcessService service = new WF_OpenProcessService();
 * WFOpenProcess portType = service.getWFOpenProcessPort();
 * portType.openProcess(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WF_OpenProcessService", targetNamespace = "http://server.ws.linkey.cn/", wsdlLocation = "http://localhost:8080/bpm/WF_OpenProcessPort?wsdl")
public class WFOpenProcessService extends Service {

    private final static URL WFOPENPROCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.linkey.ws.client.WFOpenProcessService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.linkey.ws.client.WFOpenProcessService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bpm/WF_OpenProcessPort?wsdl");
        }
        catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bpm/WF_OpenProcessPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WFOPENPROCESSSERVICE_WSDL_LOCATION = url;
    }

    public WFOpenProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFOpenProcessService() {
        super(WFOPENPROCESSSERVICE_WSDL_LOCATION, new QName("http://server.ws.linkey.cn/", "WF_OpenProcessService"));
    }

    /**
     * 
     * @return returns WFOpenProcess
     */
    @WebEndpoint(name = "WF_OpenProcessPort")
    public WFOpenProcess getWFOpenProcessPort() {
        return super.getPort(new QName("http://server.ws.linkey.cn/", "WF_OpenProcessPort"), WFOpenProcess.class);
    }

}
