package cn.linkey.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "WF_OpenProcess", targetNamespace = "http://server.ws.linkey.cn/")
public interface WFOpenProcess {

    /**
     * 
     * @param docXml
     * @param syspwd
     * @param userid
     * @param sysid
     * @param docUnid
     * @param processid
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "openProcess", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.OpenProcess")
    @ResponseWrapper(localName = "openProcessResponse", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.OpenProcessResponse")
    public String openProcess(@WebParam(name = "docXml", targetNamespace = "") String docXml, @WebParam(name = "processid", targetNamespace = "") String processid,
            @WebParam(name = "docUnid", targetNamespace = "") String docUnid, @WebParam(name = "userid", targetNamespace = "") String userid,
            @WebParam(name = "sysid", targetNamespace = "") String sysid, @WebParam(name = "syspwd", targetNamespace = "") String syspwd);

}
