package cn.linkey.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WF_RunProcessService service = new WF_RunProcessService();
 * WFRunProcess portType = service.getWFRunProcessPort();
 * portType.runProcess(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WF_RunProcessService", targetNamespace = "http://server.ws.linkey.cn/", wsdlLocation = "http://localhost:8080/bpm/WF_RunProcessPort?wsdl")
public class WFRunProcessService extends Service {

    private final static URL WFRUNPROCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.linkey.ws.client.WFRunProcessService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.linkey.ws.client.WFRunProcessService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bpm/WF_RunProcessPort?wsdl");
        }
        catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bpm/WF_RunProcessPort?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WFRUNPROCESSSERVICE_WSDL_LOCATION = url;
    }

    public WFRunProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFRunProcessService() {
        super(WFRUNPROCESSSERVICE_WSDL_LOCATION, new QName("http://server.ws.linkey.cn/", "WF_RunProcessService"));
    }

    /**
     * 
     * @return returns WFRunProcess
     */
    @WebEndpoint(name = "WF_RunProcessPort")
    public WFRunProcess getWFRunProcessPort() {
        return super.getPort(new QName("http://server.ws.linkey.cn/", "WF_RunProcessPort"), WFRunProcess.class);
    }

}
