package cn.linkey.ws.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WF_RunRuleService service = new WF_RunRuleService();
 * WFRunRule portType = service.getWFRunRulePort();
 * portType.runRule(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WF_RunRuleService", targetNamespace = "http://server.ws.linkey.cn/", wsdlLocation = "http://localhost:8080/bpm/WF_RunRulePort?wsdl")
public class WFRunRuleService extends Service {

    public WFRunRuleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFRunRuleService(URL url) {
        super(url, new QName("http://server.ws.linkey.cn/", "WF_RunRuleService"));
    }

    /**
     * 
     * @return returns WFRunRule
     */
    @WebEndpoint(name = "WF_RunRulePort")
    public WFRunRule getWFRunRulePort() {
        return super.getPort(new QName("http://server.ws.linkey.cn/", "WF_RunRulePort"), WFRunRule.class);
    }

}
