package cn.linkey.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "WF_RunProcess", targetNamespace = "http://server.ws.linkey.cn/")
public interface WFRunProcess {

    /**
     * 
     * @param nextUserList
     * @param actionid
     * @param docXml
     * @param nextNodeid
     * @param syspwd
     * @param remark
     * @param userid
     * @param sysid
     * @param docUnid
     * @param processid
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runProcess", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.RunProcess")
    @ResponseWrapper(localName = "runProcessResponse", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.RunProcessResponse")
    public String runProcess(@WebParam(name = "docXml", targetNamespace = "") String docXml, @WebParam(name = "actionid", targetNamespace = "") String actionid,
            @WebParam(name = "processid", targetNamespace = "") String processid, @WebParam(name = "docUnid", targetNamespace = "") String docUnid,
            @WebParam(name = "nextNodeid", targetNamespace = "") String nextNodeid, @WebParam(name = "nextUserList", targetNamespace = "") String nextUserList,
            @WebParam(name = "userid", targetNamespace = "") String userid, @WebParam(name = "remark", targetNamespace = "") String remark,
            @WebParam(name = "sysid", targetNamespace = "") String sysid, @WebParam(name = "syspwd", targetNamespace = "") String syspwd);

}
