package cn.linkey.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "WF_RunRule", targetNamespace = "http://server.ws.linkey.cn/")
public interface WFRunRule {

    /**
     * 
     * @param syspwd
     * @param rulenum
     * @param userid
     * @param params
     * @param sysid
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "runRule", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.RunRule")
    @ResponseWrapper(localName = "runRuleResponse", targetNamespace = "http://server.ws.linkey.cn/", className = "cn.linkey.ws.client.RunRuleResponse")
    public String runRule(@WebParam(name = "rulenum", targetNamespace = "") String rulenum, @WebParam(name = "params", targetNamespace = "") String params,
            @WebParam(name = "userid", targetNamespace = "") String userid, @WebParam(name = "sysid", targetNamespace = "") String sysid,
            @WebParam(name = "syspwd", targetNamespace = "") String syspwd);

}
