var htmlstr='<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404" codebase="linkey/bpm/word/OfficeControl.cab#version=4,0,1,1" width="100%" height="100%" >';
     htmlstr+='<param name="BorderStyle" value="0">';
	 htmlstr+='<param name="BorderColor" value="14402205">';
	 htmlstr+='<param name="TitlebarColor" value="14402205">';
     htmlstr+='<param name="TitlebarTextColor" value="0">';
     htmlstr+='<param name="Caption" value="">';
     htmlstr+='<param name="IsShowToolMenu" value="-1">';
     htmlstr+='<param name="Titlebar" value="0">';
	 htmlstr+='<param name="Toolbars" value="1">';
	 htmlstr+='<param name="IsUseUTF8Data" value="1">';
	 htmlstr+='<param name="IsUseUTF8URL" value="1">';
	 htmlstr+='<param name="Menubar" value="1">';
	 htmlstr+='<param name="MaxUploadSize" value="10000000">';
	 htmlstr+='<param name="MakerCaption" value="广州市联科软件有限公司">';
	 htmlstr+='<param name="MakerKey" value="BEDC87F526A44F654AD57D8D81604AFE5D145ACF">';
	 htmlstr+='<param name="ProductCaption" value="LINKEY">';
	 htmlstr+='<param name="ProductKey" value="18F4DB0C24E128C2EC3ED59A737F3A8F0601B988">';
	 htmlstr+='<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN></object>';
document.write(htmlstr);